# Generated by Django 2.2.12 on 2020-06-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200623_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
